name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: --ext '.js' --ext '.ts' --ext '.tsx' .

  tsc:
    name: Check typing errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - uses: icrawl/action-tsc@v1

  unit:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [lint, tsc]
    steps:
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1
    - run: |
        npm test -- --coverage
    - uses: actions/upload-artifact@v1
      with:
        name: unit-coverage
        path: coverage
